### ISSUE TITLE
Shipping checklist...

### ISSUE THREAD

**Issue by icculus** [icculus/DirkSimple#1]
Things that should be handled before shipping a first build:

- [x] Add game controller support to the SDL build.
- [x] Add a click-to-play screen for Emscripten.
- [ ] Add touch/mouse support
- [x] Test on Windows
- [x] Test on macOS
- [x] Test on Chrome
- [x] Test on Safari
- [x] Write a Patreon post
- [x] Remove Escape key as immediate app terminator.
- [x] Fix window size on Emscripten
- [x] Deal with app bundles on macOS
- [x] Make GitHub repo public

I might split these out into separate issues if they turn out to be significant effort.

**Comment by icculus** [comment]
Decided to punk on mouse and touch support for the initial release. You have to decide to stop painting at some point. I'll move it to its own issue. Everything else is done! And this shipped yesterday!
